# Generated by Django 5.1.2 on 2024-11-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Process Engineer'), ('CE', 'Control Engineer'), ('DE', 'Design Engineer')], default='PE', max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwg', models.CharField(max_length=200)),
                ('concessionRequest', models.TextField()),
                ('controlCheck', models.BooleanField(default=False)),
                ('caseOfProblem', models.TextField()),
                ('concessionReport', models.TextField()),
                ('productionList', models.TextField()),
                ('engineer', models.ManyToManyField(related_name='Issues', to='technicalIssues.engineer')),
            ],
        ),
    ]
