# Generated by Django 5.1.2 on 2024-11-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicalIssues', '0002_remove_engineer_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='productionList',
        ),
    ]
