# Generated by Django 5.1.2 on 2024-11-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicalIssues', '0003_remove_issues_productionlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='engineer',
        ),
        migrations.DeleteModel(
            name='Engineer',
        ),
    ]
